# Generated by Django 6.0.4 on 2026-04-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='cover_image',
            field=models.URLField(blank=True, help_text='Exterior or campus photo URL (HTTPS) for cards and landing page.', max_length=512),
        ),
    ]
